//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomSoft.Template.Dominio.FTPSoftrade {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTPSoftrade.IFTPSeguridadService")]
    public interface IFTPSeguridadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFTPSeguridadService/OperacionArchivo", ReplyAction="http://tempuri.org/IFTPSeguridadService/OperacionArchivoResponse")]
        CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoResponse OperacionArchivo(CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoRequest archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFTPSeguridadService/OperacionArchivo", ReplyAction="http://tempuri.org/IFTPSeguridadService/OperacionArchivoResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoResponse> OperacionArchivoAsync(CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoRequest archivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFTPSeguridadServiceChannel : CustomSoft.Template.Dominio.FTPSoftrade.IFTPSeguridadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FTPSeguridadServiceClient : System.ServiceModel.ClientBase<CustomSoft.Template.Dominio.FTPSoftrade.IFTPSeguridadService>, CustomSoft.Template.Dominio.FTPSoftrade.IFTPSeguridadService {
        
        public FTPSeguridadServiceClient() {
        }
        
        public FTPSeguridadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FTPSeguridadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTPSeguridadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTPSeguridadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoResponse OperacionArchivo(CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoRequest archivo) {
            return base.Channel.OperacionArchivo(archivo);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoResponse> OperacionArchivoAsync(CustomSoft.Template.Modelo.FTPSoftrade.RecibeArchivoRequest archivo) {
            return base.Channel.OperacionArchivoAsync(archivo);
        }
    }
}
