//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomSoft.Template.Dominio.ServiciosVUCEM {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBaseWS", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.RequestVUCEM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionRequestBaseOfRequestVUCEMfmVq_Slhw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest))]
    public partial class RequestBaseWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPassAAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pUsuarioAAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPassAA {
            get {
                return this.pPassAAField;
            }
            set {
                if ((object.ReferenceEquals(this.pPassAAField, value) != true)) {
                    this.pPassAAField = value;
                    this.RaisePropertyChanged("pPassAA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pUsuarioAA {
            get {
                return this.pUsuarioAAField;
            }
            set {
                if ((object.ReferenceEquals(this.pUsuarioAAField, value) != true)) {
                    this.pUsuarioAAField = value;
                    this.RaisePropertyChanged("pUsuarioAA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestVUCEM", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionRequestBaseOfRequestVUCEMfmVq_Slhw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest))]
    public partial class RequestVUCEM : CustomSoft.Template.Dominio.ServiciosVUCEM.RequestBaseWS {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pAduanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pContenedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pEDocumentCOVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pGuiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPatenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPedimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pRFCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFinal {
            get {
                return this.FechaFinalField;
            }
            set {
                if ((this.FechaFinalField.Equals(value) != true)) {
                    this.FechaFinalField = value;
                    this.RaisePropertyChanged("FechaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicial {
            get {
                return this.FechaInicialField;
            }
            set {
                if ((this.FechaInicialField.Equals(value) != true)) {
                    this.FechaInicialField = value;
                    this.RaisePropertyChanged("FechaInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pAduana {
            get {
                return this.pAduanaField;
            }
            set {
                if ((this.pAduanaField.Equals(value) != true)) {
                    this.pAduanaField = value;
                    this.RaisePropertyChanged("pAduana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pContenedor {
            get {
                return this.pContenedorField;
            }
            set {
                if ((object.ReferenceEquals(this.pContenedorField, value) != true)) {
                    this.pContenedorField = value;
                    this.RaisePropertyChanged("pContenedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pEDocumentCOVE {
            get {
                return this.pEDocumentCOVEField;
            }
            set {
                if ((object.ReferenceEquals(this.pEDocumentCOVEField, value) != true)) {
                    this.pEDocumentCOVEField = value;
                    this.RaisePropertyChanged("pEDocumentCOVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pGuia {
            get {
                return this.pGuiaField;
            }
            set {
                if ((object.ReferenceEquals(this.pGuiaField, value) != true)) {
                    this.pGuiaField = value;
                    this.RaisePropertyChanged("pGuia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPatente {
            get {
                return this.pPatenteField;
            }
            set {
                if ((object.ReferenceEquals(this.pPatenteField, value) != true)) {
                    this.pPatenteField = value;
                    this.RaisePropertyChanged("pPatente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPedimento {
            get {
                return this.pPedimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.pPedimentoField, value) != true)) {
                    this.pPedimentoField = value;
                    this.RaisePropertyChanged("pPedimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pRFC {
            get {
                return this.pRFCField;
            }
            set {
                if ((object.ReferenceEquals(this.pRFCField, value) != true)) {
                    this.pRFCField = value;
                    this.RaisePropertyChanged("pRFC");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionRequestBaseOfRequestVUCEMfmVq_Slhw", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest))]
    public partial class OperacionRequestBaseOfRequestVUCEMfmVq_Slhw : CustomSoft.Template.Dominio.ServiciosVUCEM.RequestVUCEM {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.ServiciosVUCEM.RequestVUCEM EntidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.ServiciosVUCEM.RequestVUCEM Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VucemOperacionRequest", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Request")]
    [System.SerializableAttribute()]
    public partial class VucemOperacionRequest : CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionRequestBaseOfRequestVUCEMfmVq_Slhw {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.ServiciosVUCEM.TipoConsulta ConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoIntentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.ServiciosVUCEM.TipoConsulta Consulta {
            get {
                return this.ConsultaField;
            }
            set {
                if ((this.ConsultaField.Equals(value) != true)) {
                    this.ConsultaField = value;
                    this.RaisePropertyChanged("Consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoIntentos {
            get {
                return this.NoIntentosField;
            }
            set {
                if ((this.NoIntentosField.Equals(value) != true)) {
                    this.NoIntentosField = value;
                    this.RaisePropertyChanged("NoIntentos");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoConsulta", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Compartido")]
    public enum TipoConsulta : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByPatente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByPedimento = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByCoveEDocument = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByRFC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByContendor = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByGuia = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByAduana = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionResponseBaseOfRequestVUCEMfmVq_Slhw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionResponseBaseOfArchivoMlU7cFfIX))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionResponseBaseOfArrayOfPedimentoVUCEMlU7cFfIX))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EjecucionValidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EjecucionValida {
            get {
                return this.EjecucionValidaField;
            }
            set {
                if ((this.EjecucionValidaField.Equals(value) != true)) {
                    this.EjecucionValidaField = value;
                    this.RaisePropertyChanged("EjecucionValida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfRequestVUCEMfmVq_Slhw", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoRequest))]
    public partial class OperacionResponseBaseOfRequestVUCEMfmVq_Slhw : CustomSoft.Template.Dominio.ServiciosVUCEM.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.ServiciosVUCEM.RequestVUCEM EntidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.ServiciosVUCEM.RequestVUCEM Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VucemOperacionPedimentoCompletoRequest", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Request")]
    [System.SerializableAttribute()]
    public partial class VucemOperacionPedimentoCompletoRequest : CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionResponseBaseOfRequestVUCEMfmVq_Slhw {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoIntentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoIntentos {
            get {
                return this.NoIntentosField;
            }
            set {
                if ((this.NoIntentosField.Equals(value) != true)) {
                    this.NoIntentosField = value;
                    this.RaisePropertyChanged("NoIntentos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfArchivoMlU7cFfIX", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoResponse))]
    public partial class OperacionResponseBaseOfArchivoMlU7cFfIX : CustomSoft.Template.Dominio.ServiciosVUCEM.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.ServiciosVUCEM.ArchivoM EntidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.ServiciosVUCEM.ArchivoM Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VucemOperacionPedimentoCompletoResponse", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Response")]
    [System.SerializableAttribute()]
    public partial class VucemOperacionPedimentoCompletoResponse : CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionResponseBaseOfArchivoMlU7cFfIX {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfArrayOfPedimentoVUCEMlU7cFfIX", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionResponse))]
    public partial class OperacionResponseBaseOfArrayOfPedimentoVUCEMlU7cFfIX : CustomSoft.Template.Dominio.ServiciosVUCEM.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.ServiciosVUCEM.PedimentoVUCEM[] EntidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.ServiciosVUCEM.PedimentoVUCEM[] Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VucemOperacionResponse", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Servicios.Response")]
    [System.SerializableAttribute()]
    public partial class VucemOperacionResponse : CustomSoft.Template.Dominio.ServiciosVUCEM.OperacionResponseBaseOfArrayOfPedimentoVUCEMlU7cFfIX {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPedimentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPedimentos {
            get {
                return this.NumeroPedimentosField;
            }
            set {
                if ((this.NumeroPedimentosField.Equals(value) != true)) {
                    this.NumeroPedimentosField = value;
                    this.RaisePropertyChanged("NumeroPedimentos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedimentoVUCEM", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class PedimentoVUCEM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAduanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroAduanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroPedimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAduana {
            get {
                return this.NombreAduanaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAduanaField, value) != true)) {
                    this.NombreAduanaField = value;
                    this.RaisePropertyChanged("NombreAduana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAduana {
            get {
                return this.NumeroAduanaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroAduanaField, value) != true)) {
                    this.NumeroAduanaField = value;
                    this.RaisePropertyChanged("NumeroAduana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumeroPedimento {
            get {
                return this.NumeroPedimentoField;
            }
            set {
                if ((this.NumeroPedimentoField.Equals(value) != true)) {
                    this.NumeroPedimentoField = value;
                    this.RaisePropertyChanged("NumeroPedimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Patente {
            get {
                return this.PatenteField;
            }
            set {
                if ((this.PatenteField.Equals(value) != true)) {
                    this.PatenteField = value;
                    this.RaisePropertyChanged("Patente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoM", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Dominio.Entidades")]
    [System.SerializableAttribute()]
    public partial class ArchivoM : CustomSoft.Template.Dominio.ServiciosVUCEM.DatosBasePedimento {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedimentoBase", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Dominio.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.DatosBasePedimento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.ArchivoM))]
    public partial class PedimentoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAduanaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAduanaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroPedimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAduanaDespacho {
            get {
                return this.NombreAduanaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAduanaDespachoField, value) != true)) {
                    this.NombreAduanaDespachoField = value;
                    this.RaisePropertyChanged("NombreAduanaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAduanaDespacho {
            get {
                return this.NumeroAduanaDespachoField;
            }
            set {
                if ((this.NumeroAduanaDespachoField.Equals(value) != true)) {
                    this.NumeroAduanaDespachoField = value;
                    this.RaisePropertyChanged("NumeroAduanaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumeroPedimento {
            get {
                return this.NumeroPedimentoField;
            }
            set {
                if ((this.NumeroPedimentoField.Equals(value) != true)) {
                    this.NumeroPedimentoField = value;
                    this.RaisePropertyChanged("NumeroPedimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Patente {
            get {
                return this.PatenteField;
            }
            set {
                if ((this.PatenteField.Equals(value) != true)) {
                    this.PatenteField = value;
                    this.RaisePropertyChanged("Patente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosBasePedimento", Namespace="http://schemas.datacontract.org/2004/07/VUCEM.Template.Modelo.Dominio.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.ServiciosVUCEM.ArchivoM))]
    public partial class DatosBasePedimento : CustomSoft.Template.Dominio.ServiciosVUCEM.PedimentoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CLaveAduanaSeccionEntradaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLaveTramiteAduaneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CURPCausanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleDomicilioIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveDestinoMercanciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveMedioTrasporteArriboAduanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveMedioTrasporteEntradaSalidaMercanciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveMedioTrasporteSalidaAduanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpAgenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadFederativaIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaElectronicaAvanzadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ImporteEmbalajesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ImporteFletesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ImporteOtrosIncrementablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ImporteSegurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreImportadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroInteriorIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroSerieCertificadoFEAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisDomicilioFiscalIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PesoBrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCAgenteAduanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCCausanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TipoCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoFiguraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoMovimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CLaveAduanaSeccionEntradaSalida {
            get {
                return this.CLaveAduanaSeccionEntradaSalidaField;
            }
            set {
                if ((this.CLaveAduanaSeccionEntradaSalidaField.Equals(value) != true)) {
                    this.CLaveAduanaSeccionEntradaSalidaField = value;
                    this.RaisePropertyChanged("CLaveAduanaSeccionEntradaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLaveTramiteAduanero {
            get {
                return this.CLaveTramiteAduaneroField;
            }
            set {
                if ((object.ReferenceEquals(this.CLaveTramiteAduaneroField, value) != true)) {
                    this.CLaveTramiteAduaneroField = value;
                    this.RaisePropertyChanged("CLaveTramiteAduanero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURPCausante {
            get {
                return this.CURPCausanteField;
            }
            set {
                if ((object.ReferenceEquals(this.CURPCausanteField, value) != true)) {
                    this.CURPCausanteField = value;
                    this.RaisePropertyChanged("CURPCausante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalleDomicilioIE {
            get {
                return this.CalleDomicilioIEField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleDomicilioIEField, value) != true)) {
                    this.CalleDomicilioIEField = value;
                    this.RaisePropertyChanged("CalleDomicilioIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveDestinoMercancia {
            get {
                return this.ClaveDestinoMercanciaField;
            }
            set {
                if ((this.ClaveDestinoMercanciaField.Equals(value) != true)) {
                    this.ClaveDestinoMercanciaField = value;
                    this.RaisePropertyChanged("ClaveDestinoMercancia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveMedioTrasporteArriboAduana {
            get {
                return this.ClaveMedioTrasporteArriboAduanaField;
            }
            set {
                if ((this.ClaveMedioTrasporteArriboAduanaField.Equals(value) != true)) {
                    this.ClaveMedioTrasporteArriboAduanaField = value;
                    this.RaisePropertyChanged("ClaveMedioTrasporteArriboAduana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveMedioTrasporteEntradaSalidaMercancia {
            get {
                return this.ClaveMedioTrasporteEntradaSalidaMercanciaField;
            }
            set {
                if ((this.ClaveMedioTrasporteEntradaSalidaMercanciaField.Equals(value) != true)) {
                    this.ClaveMedioTrasporteEntradaSalidaMercanciaField = value;
                    this.RaisePropertyChanged("ClaveMedioTrasporteEntradaSalidaMercancia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveMedioTrasporteSalidaAduana {
            get {
                return this.ClaveMedioTrasporteSalidaAduanaField;
            }
            set {
                if ((this.ClaveMedioTrasporteSalidaAduanaField.Equals(value) != true)) {
                    this.ClaveMedioTrasporteSalidaAduanaField = value;
                    this.RaisePropertyChanged("ClaveMedioTrasporteSalidaAduana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveOperacion {
            get {
                return this.ClaveOperacionField;
            }
            set {
                if ((this.ClaveOperacionField.Equals(value) != true)) {
                    this.ClaveOperacionField = value;
                    this.RaisePropertyChanged("ClaveOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostalIE {
            get {
                return this.CodigoPostalIEField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalIEField, value) != true)) {
                    this.CodigoPostalIEField = value;
                    this.RaisePropertyChanged("CodigoPostalIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurpAgente {
            get {
                return this.CurpAgenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpAgenteField, value) != true)) {
                    this.CurpAgenteField = value;
                    this.RaisePropertyChanged("CurpAgente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntidadFederativaIE {
            get {
                return this.EntidadFederativaIEField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadFederativaIEField, value) != true)) {
                    this.EntidadFederativaIEField = value;
                    this.RaisePropertyChanged("EntidadFederativaIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmaElectronicaAvanzada {
            get {
                return this.FirmaElectronicaAvanzadaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaElectronicaAvanzadaField, value) != true)) {
                    this.FirmaElectronicaAvanzadaField = value;
                    this.RaisePropertyChanged("FirmaElectronicaAvanzada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ImporteEmbalajes {
            get {
                return this.ImporteEmbalajesField;
            }
            set {
                if ((this.ImporteEmbalajesField.Equals(value) != true)) {
                    this.ImporteEmbalajesField = value;
                    this.RaisePropertyChanged("ImporteEmbalajes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ImporteFletes {
            get {
                return this.ImporteFletesField;
            }
            set {
                if ((this.ImporteFletesField.Equals(value) != true)) {
                    this.ImporteFletesField = value;
                    this.RaisePropertyChanged("ImporteFletes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ImporteOtrosIncrementables {
            get {
                return this.ImporteOtrosIncrementablesField;
            }
            set {
                if ((this.ImporteOtrosIncrementablesField.Equals(value) != true)) {
                    this.ImporteOtrosIncrementablesField = value;
                    this.RaisePropertyChanged("ImporteOtrosIncrementables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ImporteSeguros {
            get {
                return this.ImporteSegurosField;
            }
            set {
                if ((this.ImporteSegurosField.Equals(value) != true)) {
                    this.ImporteSegurosField = value;
                    this.RaisePropertyChanged("ImporteSeguros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipioIE {
            get {
                return this.MunicipioIEField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioIEField, value) != true)) {
                    this.MunicipioIEField = value;
                    this.RaisePropertyChanged("MunicipioIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreImportador {
            get {
                return this.NombreImportadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreImportadorField, value) != true)) {
                    this.NombreImportadorField = value;
                    this.RaisePropertyChanged("NombreImportador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExteriorIE {
            get {
                return this.NumeroExteriorIEField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorIEField, value) != true)) {
                    this.NumeroExteriorIEField = value;
                    this.RaisePropertyChanged("NumeroExteriorIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroInteriorIE {
            get {
                return this.NumeroInteriorIEField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroInteriorIEField, value) != true)) {
                    this.NumeroInteriorIEField = value;
                    this.RaisePropertyChanged("NumeroInteriorIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroSerieCertificadoFEA {
            get {
                return this.NumeroSerieCertificadoFEAField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroSerieCertificadoFEAField, value) != true)) {
                    this.NumeroSerieCertificadoFEAField = value;
                    this.RaisePropertyChanged("NumeroSerieCertificadoFEA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisDomicilioFiscalIE {
            get {
                return this.PaisDomicilioFiscalIEField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisDomicilioFiscalIEField, value) != true)) {
                    this.PaisDomicilioFiscalIEField = value;
                    this.RaisePropertyChanged("PaisDomicilioFiscalIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PesoBruto {
            get {
                return this.PesoBrutoField;
            }
            set {
                if ((this.PesoBrutoField.Equals(value) != true)) {
                    this.PesoBrutoField = value;
                    this.RaisePropertyChanged("PesoBruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCAgenteAduanal {
            get {
                return this.RFCAgenteAduanalField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCAgenteAduanalField, value) != true)) {
                    this.RFCAgenteAduanalField = value;
                    this.RaisePropertyChanged("RFCAgenteAduanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCCausante {
            get {
                return this.RFCCausanteField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCCausanteField, value) != true)) {
                    this.RFCCausanteField = value;
                    this.RaisePropertyChanged("RFCCausante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TipoCambio {
            get {
                return this.TipoCambioField;
            }
            set {
                if ((this.TipoCambioField.Equals(value) != true)) {
                    this.TipoCambioField = value;
                    this.RaisePropertyChanged("TipoCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoFigura {
            get {
                return this.TipoFiguraField;
            }
            set {
                if ((this.TipoFiguraField.Equals(value) != true)) {
                    this.TipoFiguraField = value;
                    this.RaisePropertyChanged("TipoFigura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoMovimiento {
            get {
                return this.TipoMovimientoField;
            }
            set {
                if ((this.TipoMovimientoField.Equals(value) != true)) {
                    this.TipoMovimientoField = value;
                    this.RaisePropertyChanged("TipoMovimiento");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosVUCEM.ISeguridadService")]
    public interface ISeguridadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/InvocaVUCEMListados", ReplyAction="http://tempuri.org/ISeguridadService/InvocaVUCEMListadosResponse")]
        CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionResponse InvocaVUCEMListados(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/InvocaVUCEMListados", ReplyAction="http://tempuri.org/ISeguridadService/InvocaVUCEMListadosResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionResponse> InvocaVUCEMListadosAsync(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/InvocaVUCEMPedimentoCompleto", ReplyAction="http://tempuri.org/ISeguridadService/InvocaVUCEMPedimentoCompletoResponse")]
        CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoResponse InvocaVUCEMPedimentoCompleto(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridadService/InvocaVUCEMPedimentoCompleto", ReplyAction="http://tempuri.org/ISeguridadService/InvocaVUCEMPedimentoCompletoResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoResponse> InvocaVUCEMPedimentoCompletoAsync(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoRequest pRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeguridadServiceChannel : CustomSoft.Template.Dominio.ServiciosVUCEM.ISeguridadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadServiceClient : System.ServiceModel.ClientBase<CustomSoft.Template.Dominio.ServiciosVUCEM.ISeguridadService>, CustomSoft.Template.Dominio.ServiciosVUCEM.ISeguridadService {
        
        public SeguridadServiceClient() {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionResponse InvocaVUCEMListados(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest pRequest) {
            return base.Channel.InvocaVUCEMListados(pRequest);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionResponse> InvocaVUCEMListadosAsync(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionRequest pRequest) {
            return base.Channel.InvocaVUCEMListadosAsync(pRequest);
        }
        
        public CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoResponse InvocaVUCEMPedimentoCompleto(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoRequest pRequest) {
            return base.Channel.InvocaVUCEMPedimentoCompleto(pRequest);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoResponse> InvocaVUCEMPedimentoCompletoAsync(CustomSoft.Template.Dominio.ServiciosVUCEM.VucemOperacionPedimentoCompletoRequest pRequest) {
            return base.Channel.InvocaVUCEMPedimentoCompletoAsync(pRequest);
        }
    }
}
