//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomSoft.Template.Dominio.CatalogosFiltrosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.ResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.OperacionResponseBaseOfListaCatalogoPersonalizadoString0caiiWiN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.OperacionRequestBaseOfFiltrosBusqueda0caiiWiN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioEjecucionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioEjecucion {
            get {
                return this.IdUsuarioEjecucionField;
            }
            set {
                if ((this.IdUsuarioEjecucionField.Equals(value) != true)) {
                    this.IdUsuarioEjecucionField = value;
                    this.RaisePropertyChanged("IdUsuarioEjecucion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.OperacionResponseBaseOfListaCatalogoPersonalizadoString0caiiWiN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse))]
    public partial class ResponseBase : CustomSoft.Template.Dominio.CatalogosFiltrosService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EjecucionValidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EjecucionValida {
            get {
                return this.EjecucionValidaField;
            }
            set {
                if ((this.EjecucionValidaField.Equals(value) != true)) {
                    this.EjecucionValidaField = value;
                    this.RaisePropertyChanged("EjecucionValida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfListaCatalogoPersonalizadoString0caiiWiN", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse))]
    public partial class OperacionResponseBaseOfListaCatalogoPersonalizadoString0caiiWiN : CustomSoft.Template.Dominio.CatalogosFiltrosService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.ListaCatalogoPersonalizadoString ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.ListaCatalogoPersonalizadoString Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoPersonalizadoStringResponse", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Servicios.Respo" +
        "nse")]
    [System.SerializableAttribute()]
    public partial class CatalogoPersonalizadoStringResponse : CustomSoft.Template.Dominio.CatalogosFiltrosService.OperacionResponseBaseOfListaCatalogoPersonalizadoString0caiiWiN {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionRequestBaseOfFiltrosBusqueda0caiiWiN", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Servicios.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoRequest))]
    public partial class OperacionRequestBaseOfFiltrosBusqueda0caiiWiN : CustomSoft.Template.Dominio.CatalogosFiltrosService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.FiltrosBusqueda ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.FiltrosBusqueda Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoPersonalizadoRequest", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Servicios.Reque" +
        "st")]
    [System.SerializableAttribute()]
    public partial class CatalogoPersonalizadoRequest : CustomSoft.Template.Dominio.CatalogosFiltrosService.OperacionRequestBaseOfFiltrosBusqueda0caiiWiN {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.ProgramaFiltro ProgramaFiltroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.ProgramaFiltro ProgramaFiltro {
            get {
                return this.ProgramaFiltroField;
            }
            set {
                if ((this.ProgramaFiltroField.Equals(value) != true)) {
                    this.ProgramaFiltroField = value;
                    this.RaisePropertyChanged("ProgramaFiltro");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltrosBusqueda", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Dominio.Entidad" +
        "es")]
    [System.SerializableAttribute()]
    public partial class FiltrosBusqueda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.EnumeradoresCatalogoPersonalizadoGPAduanalString BusquedaGPAduanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.EnumeradoresCatalogoPersonalizadoSoftradeString BusquedaSoftradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnInglesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.EnumeradoresCatalogoPersonalizadoGPAduanalString BusquedaGPAduanal {
            get {
                return this.BusquedaGPAduanalField;
            }
            set {
                if ((this.BusquedaGPAduanalField.Equals(value) != true)) {
                    this.BusquedaGPAduanalField = value;
                    this.RaisePropertyChanged("BusquedaGPAduanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.EnumeradoresCatalogoPersonalizadoSoftradeString BusquedaSoftrade {
            get {
                return this.BusquedaSoftradeField;
            }
            set {
                if ((this.BusquedaSoftradeField.Equals(value) != true)) {
                    this.BusquedaSoftradeField = value;
                    this.RaisePropertyChanged("BusquedaSoftrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnIngles {
            get {
                return this.EnInglesField;
            }
            set {
                if ((this.EnInglesField.Equals(value) != true)) {
                    this.EnInglesField = value;
                    this.RaisePropertyChanged("EnIngles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa {
            get {
                return this.IdEmpresaField;
            }
            set {
                if ((this.IdEmpresaField.Equals(value) != true)) {
                    this.IdEmpresaField = value;
                    this.RaisePropertyChanged("IdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramaFiltro", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Compartido")]
    public enum ProgramaFiltro : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GPAduanal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Softrade = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaCatalogoPersonalizadoString", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Dominio.Entidad" +
        "es")]
    [System.SerializableAttribute()]
    public partial class ListaCatalogoPersonalizadoString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoString[] ListaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoString[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoPersonalizadoString", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Dominio.Entidad" +
        "es")]
    [System.SerializableAttribute()]
    public partial class CatalogoPersonalizadoString : CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosFiltrosService.EnumeradoresCatalogoPersonalizadoGPAduanalString CatalogoPersonalizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.EnumeradoresCatalogoPersonalizadoGPAduanalString CatalogoPersonalizado {
            get {
                return this.CatalogoPersonalizadoField;
            }
            set {
                if ((this.CatalogoPersonalizadoField.Equals(value) != true)) {
                    this.CatalogoPersonalizadoField = value;
                    this.RaisePropertyChanged("CatalogoPersonalizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion2 {
            get {
                return this.Descripcion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion2Field, value) != true)) {
                    this.Descripcion2Field = value;
                    this.RaisePropertyChanged("Descripcion2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoPersonalizadoBase", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Dominio.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoString))]
    public partial class CatalogoPersonalizadoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumeradoresCatalogoPersonalizadoGPAduanalString", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Compartido")]
    public enum EnumeradoresCatalogoPersonalizadoGPAduanalString : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientesInspeccion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EstatusInspeccion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pais = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProveedorInspeccion = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResultadoInspeccion = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoEmbarque = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZonaInspeccion = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumeradoresCatalogoPersonalizadoSoftradeString", Namespace="http://schemas.datacontract.org/2004/07/GPFiltros.Template.Modelo.Compartido")]
    public enum EnumeradoresCatalogoPersonalizadoSoftradeString : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aduana = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogosFiltrosService.IGPFiltrosService")]
    public interface IGPFiltrosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPFiltrosService/CatalogoPersonalizadoString", ReplyAction="http://tempuri.org/IGPFiltrosService/CatalogoPersonalizadoStringResponse")]
        CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse CatalogoPersonalizadoString(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPFiltrosService/CatalogoPersonalizadoString", ReplyAction="http://tempuri.org/IGPFiltrosService/CatalogoPersonalizadoStringResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse> CatalogoPersonalizadoStringAsync(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGPFiltrosServiceChannel : CustomSoft.Template.Dominio.CatalogosFiltrosService.IGPFiltrosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPFiltrosServiceClient : System.ServiceModel.ClientBase<CustomSoft.Template.Dominio.CatalogosFiltrosService.IGPFiltrosService>, CustomSoft.Template.Dominio.CatalogosFiltrosService.IGPFiltrosService {
        
        public GPFiltrosServiceClient() {
        }
        
        public GPFiltrosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPFiltrosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPFiltrosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPFiltrosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse CatalogoPersonalizadoString(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoRequest request) {
            return base.Channel.CatalogoPersonalizadoString(request);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoStringResponse> CatalogoPersonalizadoStringAsync(CustomSoft.Template.Dominio.CatalogosFiltrosService.CatalogoPersonalizadoRequest request) {
            return base.Channel.CatalogoPersonalizadoStringAsync(request);
        }
    }
}
