//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomSoft.Template.Dominio.CatalogosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfEntidadCatalogocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfArrayOfEntidadCatalogocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfArrayOfEntidadCatalogoGPcYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionRequestBaseOfCatalogoRequeridocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionRequestBaseOfCatalogoGPRequeridocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionRequestBaseOfEntidadCatalogocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioEjecucionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioEjecucion {
            get {
                return this.IdUsuarioEjecucionField;
            }
            set {
                if ((this.IdUsuarioEjecucionField.Equals(value) != true)) {
                    this.IdUsuarioEjecucionField = value;
                    this.RaisePropertyChanged("IdUsuarioEjecucion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfEntidadCatalogocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfArrayOfEntidadCatalogocYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfArrayOfEntidadCatalogoGPcYoVAI_SS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse))]
    public partial class ResponseBase : CustomSoft.Template.Dominio.CatalogosService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EjecucionValidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EjecucionValida {
            get {
                return this.EjecucionValidaField;
            }
            set {
                if ((this.EjecucionValidaField.Equals(value) != true)) {
                    this.EjecucionValidaField = value;
                    this.RaisePropertyChanged("EjecucionValida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfEntidadCatalogocYoVAI_SS", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse))]
    public partial class OperacionResponseBaseOfEntidadCatalogocYoVAI_SS : CustomSoft.Template.Dominio.CatalogosService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoGeneralOperacionResponse", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Response")]
    [System.SerializableAttribute()]
    public partial class CatalogoGeneralOperacionResponse : CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfEntidadCatalogocYoVAI_SS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfArrayOfEntidadCatalogocYoVAI_SS", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse))]
    public partial class OperacionResponseBaseOfArrayOfEntidadCatalogocYoVAI_SS : CustomSoft.Template.Dominio.CatalogosService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo[] ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo[] Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListadoCatalogoGeneralOperacionResponse", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Response")]
    [System.SerializableAttribute()]
    public partial class ListadoCatalogoGeneralOperacionResponse : CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfArrayOfEntidadCatalogocYoVAI_SS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponseBaseOfArrayOfEntidadCatalogoGPcYoVAI_SS", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse))]
    public partial class OperacionResponseBaseOfArrayOfEntidadCatalogoGPcYoVAI_SS : CustomSoft.Template.Dominio.CatalogosService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogoGP[] ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogoGP[] Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListadoCatalogoGeneralGPOperacionResponse", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Response")]
    [System.SerializableAttribute()]
    public partial class ListadoCatalogoGeneralGPOperacionResponse : CustomSoft.Template.Dominio.CatalogosService.OperacionResponseBaseOfArrayOfEntidadCatalogoGPcYoVAI_SS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionRequestBaseOfCatalogoRequeridocYoVAI_SS", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionRequest))]
    public partial class OperacionRequestBaseOfCatalogoRequeridocYoVAI_SS : CustomSoft.Template.Dominio.CatalogosService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.CatalogoRequerido ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.CatalogoRequerido Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListadoCatalogoGeneralOperacionRequest", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Request")]
    [System.SerializableAttribute()]
    public partial class ListadoCatalogoGeneralOperacionRequest : CustomSoft.Template.Dominio.CatalogosService.OperacionRequestBaseOfCatalogoRequeridocYoVAI_SS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionRequestBaseOfCatalogoGPRequeridocYoVAI_SS", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionRequest))]
    public partial class OperacionRequestBaseOfCatalogoGPRequeridocYoVAI_SS : CustomSoft.Template.Dominio.CatalogosService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.CatalogoGPRequerido ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.CatalogoGPRequerido Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListadoCatalogoGeneralGPOperacionRequest", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Request")]
    [System.SerializableAttribute()]
    public partial class ListadoCatalogoGeneralGPOperacionRequest : CustomSoft.Template.Dominio.CatalogosService.OperacionRequestBaseOfCatalogoGPRequeridocYoVAI_SS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionRequestBaseOfEntidadCatalogocYoVAI_SS", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionRequest))]
    public partial class OperacionRequestBaseOfEntidadCatalogocYoVAI_SS : CustomSoft.Template.Dominio.CatalogosService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoGeneralOperacionRequest", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Servicio" +
        "s.Request")]
    [System.SerializableAttribute()]
    public partial class CatalogoGeneralOperacionRequest : CustomSoft.Template.Dominio.CatalogosService.OperacionRequestBaseOfEntidadCatalogocYoVAI_SS {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.TipoExtraccionCatalogo ExtraccionCatalogoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.TipoExtraccionCatalogo ExtraccionCatalogo {
            get {
                return this.ExtraccionCatalogoField;
            }
            set {
                if ((this.ExtraccionCatalogoField.Equals(value) != true)) {
                    this.ExtraccionCatalogoField = value;
                    this.RaisePropertyChanged("ExtraccionCatalogo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadCatalogo", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Entidades")]
    [System.SerializableAttribute()]
    public partial class EntidadCatalogo : CustomSoft.Template.Dominio.CatalogosService.CatalogosBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoExtraccionCatalogo", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Comparti" +
        "do")]
    public enum TipoExtraccionCatalogo : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExtraerIdXAbreviatura = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExtraerIdXNombre = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogosBase", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogo))]
    public partial class CatalogosBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.Catalogo CatalogoALlamarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.Filtrado FiltradoEspecificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.Catalogo CatalogoALlamar {
            get {
                return this.CatalogoALlamarField;
            }
            set {
                if ((this.CatalogoALlamarField.Equals(value) != true)) {
                    this.CatalogoALlamarField = value;
                    this.RaisePropertyChanged("CatalogoALlamar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.Filtrado FiltradoEspecifico {
            get {
                return this.FiltradoEspecificoField;
            }
            set {
                if ((this.FiltradoEspecificoField.Equals(value) != true)) {
                    this.FiltradoEspecificoField = value;
                    this.RaisePropertyChanged("FiltradoEspecifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Catalogo", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Comparti" +
        "do")]
    public enum Catalogo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AduanaSeccion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AduanaSeccionXEntidadFederativa = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClavePedimento = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContribucionGravamenDerecho = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Destino = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EntidadFederativa = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormaPago = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fraccion = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MedioTransporte = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MetodoValoracion = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moneda = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pais = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TerminoFactura = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoComprobante = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoContenedor = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoDocumento = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoFigura = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoGuia = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoMovimiento = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoOperacion = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoPruebaSuficiente = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoTasa = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnidadMedida = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Identificador = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regulacion = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Permiso = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vinculacion = 26,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filtrado", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Comparti" +
        "do")]
    public enum Filtrado : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alias = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descripcion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abreviacion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Id = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadCatalogoGP", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Entidades")]
    [System.SerializableAttribute()]
    public partial class EntidadCatalogoGP : CustomSoft.Template.Dominio.CatalogosService.CatalogosGPBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogosGPBase", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.EntidadCatalogoGP))]
    public partial class CatalogosGPBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.Catalogo CatalogoALlamarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.Filtrado FiltradoEspecificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.Catalogo CatalogoALlamar {
            get {
                return this.CatalogoALlamarField;
            }
            set {
                if ((this.CatalogoALlamarField.Equals(value) != true)) {
                    this.CatalogoALlamarField = value;
                    this.RaisePropertyChanged("CatalogoALlamar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.Filtrado FiltradoEspecifico {
            get {
                return this.FiltradoEspecificoField;
            }
            set {
                if ((this.FiltradoEspecificoField.Equals(value) != true)) {
                    this.FiltradoEspecificoField = value;
                    this.RaisePropertyChanged("FiltradoEspecifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoRequerido", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Entidades")]
    [System.SerializableAttribute()]
    public partial class CatalogoRequerido : CustomSoft.Template.Dominio.CatalogosService.CatalogoRequeridoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoRequeridoBase", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoRequerido))]
    public partial class CatalogoRequeridoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.Catalogo CatalogoALlamarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.Catalogo CatalogoALlamar {
            get {
                return this.CatalogoALlamarField;
            }
            set {
                if ((this.CatalogoALlamarField.Equals(value) != true)) {
                    this.CatalogoALlamarField = value;
                    this.RaisePropertyChanged("CatalogoALlamar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoGPRequerido", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Entidades")]
    [System.SerializableAttribute()]
    public partial class CatalogoGPRequerido : CustomSoft.Template.Dominio.CatalogosService.CatalogoGPRequeridoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoGPRequeridoBase", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Dominio." +
        "Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomSoft.Template.Dominio.CatalogosService.CatalogoGPRequerido))]
    public partial class CatalogoGPRequeridoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomSoft.Template.Dominio.CatalogosService.CatalogoGP CatalogoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomSoft.Template.Dominio.CatalogosService.CatalogoGP Catalogo {
            get {
                return this.CatalogoField;
            }
            set {
                if ((this.CatalogoField.Equals(value) != true)) {
                    this.CatalogoField = value;
                    this.RaisePropertyChanged("Catalogo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoGP", Namespace="http://schemas.datacontract.org/2004/07/CatalogosService.Template.Modelo.Comparti" +
        "do")]
    public enum CatalogoGP : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aduana = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cliente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZonaInspeccion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoInspeccion = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoEmbarque = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogosService.ICatalogosService")]
    public interface ICatalogosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosService/ExtraerCatalogoItem", ReplyAction="http://tempuri.org/ICatalogosService/ExtraerCatalogoItemResponse")]
        CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse ExtraerCatalogoItem(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosService/ExtraerCatalogoItem", ReplyAction="http://tempuri.org/ICatalogosService/ExtraerCatalogoItemResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse> ExtraerCatalogoItemAsync(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogo", ReplyAction="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogoResponse")]
        CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse ExtraerListadoCatalogo(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogo", ReplyAction="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogoResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse> ExtraerListadoCatalogoAsync(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogoGP", ReplyAction="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogoGPResponse")]
        CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse ExtraerListadoCatalogoGP(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogoGP", ReplyAction="http://tempuri.org/ICatalogosService/ExtraerListadoCatalogoGPResponse")]
        System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse> ExtraerListadoCatalogoGPAsync(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogosServiceChannel : CustomSoft.Template.Dominio.CatalogosService.ICatalogosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogosServiceClient : System.ServiceModel.ClientBase<CustomSoft.Template.Dominio.CatalogosService.ICatalogosService>, CustomSoft.Template.Dominio.CatalogosService.ICatalogosService {
        
        public CatalogosServiceClient() {
        }
        
        public CatalogosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse ExtraerCatalogoItem(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionRequest request) {
            return base.Channel.ExtraerCatalogoItem(request);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionResponse> ExtraerCatalogoItemAsync(CustomSoft.Template.Dominio.CatalogosService.CatalogoGeneralOperacionRequest request) {
            return base.Channel.ExtraerCatalogoItemAsync(request);
        }
        
        public CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse ExtraerListadoCatalogo(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionRequest request) {
            return base.Channel.ExtraerListadoCatalogo(request);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionResponse> ExtraerListadoCatalogoAsync(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralOperacionRequest request) {
            return base.Channel.ExtraerListadoCatalogoAsync(request);
        }
        
        public CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse ExtraerListadoCatalogoGP(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionRequest request) {
            return base.Channel.ExtraerListadoCatalogoGP(request);
        }
        
        public System.Threading.Tasks.Task<CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionResponse> ExtraerListadoCatalogoGPAsync(CustomSoft.Template.Dominio.CatalogosService.ListadoCatalogoGeneralGPOperacionRequest request) {
            return base.Channel.ExtraerListadoCatalogoGPAsync(request);
        }
    }
}
